<html>
    <body>
        <div class="container">
            <div class="col-md-offset-3 col-md-6">       
                <div class="panel panel-info" style="margin-top: 150px">
                    <div class="panel-heading" > 
                        <h3 class="panel-title">
                            User Request 
                        </h3>
                    </div>
                    <div class="panel-body">  
                        <?php
                        echo $this->form;
                        ?>
                    </div>
                </div>  
            </div>
        </div>
    </body>
</html>