
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>                        
            </button>
            <a class="navbar-brand" href="#">WebSiteName</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Home</a></li>

                <li><a href="<?php echo $this->baseUrl() ?>/user/list"> Users </a></li>
                <li><a href="<?php echo $this->baseUrl() ?>/category/list"> Categories </a></li>
                <li><a href="<?php echo $this->baseUrl() ?>/course/list"> Courses </a></li>
                <li><a href="<?php echo $this->baseUrl() ?>/request/list"> Requests </a></li>
                <li><a href="<?php echo $this->baseUrl() ?>/material/list"> Materials </a></li>
                <li><a href="#"> Comments </a></li>


            </ul>


            <ul class="nav navbar-nav navbar-right">
                <li><a href="<?php echo $this->baseUrl() ?>/user/logout"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>

            </ul>

        </div>
    </div>
</nav>
