
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>                        
            </button>
            <a class="navbar-brand" href="<?php echo $this->baseUrl() ?>">WebSiteName</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="<?php echo $this->baseUrl() ?>/user/homeuser">Home</a></li>


            </ul>


            <ul class="nav navbar-nav navbar-right">
                <li><a href="<?php echo $this->baseUrl() ?>/user/add"><p class="glyphicon glyphicon-sign-up"></p> Sign Up</a></li>
            </ul>

        </div>
    </div>
</nav>
