<html>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-md-offset-11 col-md-1">
                    <a class="btn btn-primary" href='<?php echo $this->baseUrl() ?>/category/add'>Add category</a>
                </div>  
                <div class="col-md-12">

                    <div class="table-responsive">
                        <table class="table table-hover" style="margin-top: 20px ">
                            <tr class="info"> 
                                <td class="text-center">Category Name</td> 
                                <td class="text-center">Edit</td>
                                <td class="text-center">Delete</td>
                                <td class="text-center">Add Course</td>
                            </tr>
                            <?php
                            for ($i = 0; $i < count($this->categories); $i++) {
                                echo '<tr>';
                                foreach ($this->categories[$i] as $key => $value):
                                    if ($key != 'category_id') {
                                        echo '<td class="text-center">';
                                        echo $value;
                                    }
                                endforeach;
                                ?>
                                <td class="text-center">
                                    <a class="btn btn-info" href="<?php echo $this->baseUrl() ?>/category/edit/category_id/<?php echo $this->categories[$i]['category_id']; ?>" > Edit </a>
                                </td>
                                <td class="text-center">
                                    <a class="btn btn-danger" href="<?php echo $this->baseUrl() ?>/category/delete/category_id/<?php echo $this->categories[$i]['category_id']; ?>" > Delete </a>
                                </td>
                                <td class="text-center">
                                    <a class="btn btn-primary" href="<?php echo $this->baseUrl() ?>/category//<?php echo $this->categories[$i]['category_id']; ?>" > Add </a>
                                </td>
                                </tr>
                            <?php } ?>
                        </table>
                        </html>
