<html>
    <body>
        <div class="container">
            <div class="col-md-offset-3 col-md-6">       
                <div class="panel panel-info" style="margin-top: 150px">
                        <div class="panel-heading" > 
                            <h3 class="panel-title">
                                Add Course
                            </h3>
                        </div>
                        <div class="panel-body"> 
                        <label>Category Name</label>
                        
                        <input class="form-control" type="text" name="categoryname" value="<?php echo  $this->category_name ?>" readonly="readonly">
                            <?php
                            echo $this->form;
                            ?>
                        </div>
                    
                </div>  
            </div>
        </div>
    </body>
</html>
