<html>
    <body>
        <div class="container">
            <div class="row" 
                <div class="col-md-12">

                    <div class="table-responsive">
                        <table class="table table-hover" style="margin-top: 20px ">
                            <tr class="info"> 
                                <td class="text-center">Category Name</td>
                                <td class="text-center">Course Name</td> 
                                <td class="text-center">Material Name</td> 
                                <td class="text-center">Edit</td>
                                <td class="text-center">Delete</td>
                                <td class="text-center">Add Material</td>
                            </tr>
                            <?php
                            for ($i = 0; $i < count($this->courses); $i++) {
                               
                                echo '<tr>';
                                foreach ($this->courses[$i] as $key => $value):
                                      if ($key == 'category_id') {
                                        echo '<td class="text-center">';
                                        echo $value;
                                    }
                                    if ($key == 'course_id') {
                                        echo '<td class="text-center">';
                                        echo $value;
                                    }
                                endforeach;
                                ?>
                                <td class="text-center">
                                    <a class="btn btn-info" href="#" > Edit </a>
                                </td>
                                <td class="text-center">
                                    <a class="btn btn-danger" href="<?php echo $this->baseUrl() ?>/course/delete/course_name/<?php echo $this->courses[$i]['course_id']; ?>" > Delete </a>
                                </td>
                                <td class="text-center">
                                    <a class="btn btn-primary" href="<?php echo $this->baseUrl() ?>/material/add/category_name/<?php echo $this->courses[$i]['category_id']; ?>/course_name/<?php echo $this->courses[$i]['course_id']; ?>" > Add </a>
                                </td>
                                </tr>
                            <?php } ?>
                        </table>
                        </html>
