
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href= "/zend-project/bootstrap-3.3.2-dist/css/bootstrap.css">
		<link rel="stylesheet" href= "/zend-project/bootstrap-3.3.2-dist/css/bootstrap-theme.css">
		<script src="/zend-project/jquery-2.1.3.min.js" type="text/javascript"></script>
		<script src="/zend-project/bootstrap-3.3.2-dist/js/bootstrap.js" type="text/javascript"></script>
	</head>


<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        
        <li><a href="<?php echo $this->baseUrl() ?>/user/list"> Users </a></li>
        <li><a href="<?php echo $this->baseUrl() ?>/category/list"> Categories </a></li>
        <li><a href="<?php echo $this->baseUrl() ?>/course/list"> Courses </a></li>
        <li><a href="<?php echo $this->baseUrl() ?>/material/list"> Materials </a></li>
        <li><a href="#"> Comments </a></li>


      </ul>

      
      <ul class="nav navbar-nav navbar-right">

          <li><a href="http://localhost/zend-project/public/user/add"><p class="glyphicon glyphicon-sign-up"></p> Sign Up</a></li>

        <li><a href="http://localhost/PHP-Project/docs/Forget_Password.php"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
        
      </ul>

    </div>
  </div>
</nav>

<?php echo $this->layout()->content; ?>