<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href= "/zend-project/public/bootstrap-3.3.2-dist/css/bootstrap.css">
    <link rel="stylesheet" href= "/zend-project/public/bootstrap-3.3.2-dist/css/bootstrap-theme.css">
    <script src="/zend-project/public/jquery-2.1.3.min.js" type="text/javascript"></script>
    <script src="/zend-project/public/bootstrap-3.3.2-dist/js/bootstrap.js" type="text/javascript"></script>
</head>

<?php
$DOCUMENT_ROOT = $_SERVER['DOCUMENT_ROOT'];
$authorization = Zend_Auth::getInstance();
$user_info = $authorization->getStorage()->read();
if ($user_info != NULL) {
    if ($user_info->is_admin == 1) {
        include ($DOCUMENT_ROOT . '/zend-project/public/design/adminheader.phtml');
    } elseif ($user_info->is_admin == 0) {
        include ($DOCUMENT_ROOT . '/zend-project/public/design/userheader.phtml');
    }
} else {
    include ($DOCUMENT_ROOT . '/zend-project/public/design/guestheader.phtml');
}


echo $this->layout()->content;
?>
