<html>
    <body>
        <div class="container">
            <div class="col-md-offset-3 col-md-6">       
                <div class="panel panel-info" style="margin-top: 150px">
                    <div class="panel-heading" > 
                        <h3 class="panel-title">
                            System statistics 
                        </h3>
                    </div>
                    <div class="panel-body">  
                        <?php
                        $number_of_users = count($this->allusers);
                        echo '<h4 class="glyphicon glyphicon-user">Number_of_users=' . $number_of_users . '</h4>';
                        echo '<br>';
                        echo '<h4 class="glyphicon glyphicon-download">Number_of_downloads: <a href=' . $this->baseUrl() . '/material/list>Materials</a></h4>';
                        ?>
                    </div>
                </div>  
            </div>
        </div>
    </body>
</html>
