<html>
    <body>
        <div class="container">
            <div class="row">

                <div class="col-md-offset-11 col-md-1">
                    <a class="btn btn-primary" href='<?php echo $this->baseUrl() ?>/user/add'>Add user</a>
                </div>  
                <div class="col-md-12">

                    <div class="table-responsive">
                        <table class="table table-hover" style="margin-top: 20px ">
                            <tr class="info">                   
                                <td class="text-center">User Name</td>
                                <td class="text-center">Gender</td>
                                <td class="text-center">Country</td>
                                <td class="text-center">Signature</td>
                                <td class="text-center">Email</td>
                                <td class="text-center">Profile Picture</td>
                                <td class="text-center">Admin/User</td>
                                <td class="text-center">Banned Users</td>
                                <td class="text-center">Edit</td>
                                <td class="text-center">Delete</td>
                            </tr>

                            <?php
                            for ($i = 0; $i < count($this->users); $i++) {
                                echo '<tr>';
                                foreach ($this->users[$i] as $key => $value):
                                    if ($key != 'user_id' && $key != 'password') {
                                        $id = $this->users[$i]['user_id'];
                                        echo '<td class="text-center">';
                                        if ($key == 'user_photo') {
                                            echo "<img src='/zend-project/public/images/users/$value' width='80' height='80'/>";
                                        } elseif ($key == 'is_admin') {
                                            if ($value == '1') {
                                                echo 'Admin';
                                                echo '<br>';
                                                echo "<a href='./adminuser/user_id/$id'>To User </a>";
                                            } else {
                                                echo 'User';
                                                echo '<br>';
                                                echo "<a href='./adminuser/user_id/$id'>To Admin </a>";
                                            }
                                        } elseif ($key == 'is_banned') {
                                            if ($value == '1') {
                                                echo 'Banned';
                                                echo '<br>';
                                                echo "<a href='./banunban/user_id/$id'>Unban </a>";
                                            } else {
                                                echo 'Unbanned';
                                                echo '<br>';
                                                echo "<a href='./banunban/user_id/$id'>Ban </a>";
                                            }
                                        } else {
                                            echo $value;
                                        }
                                    }
                                endforeach;
                                ?>
                                <td>
                                    <a class="btn btn-info" href="<?php echo $this->baseUrl() ?>/user/edit/adminuser_id/<?php echo $this->users[$i]['user_id']; ?>" > Edit </a>
                                </td>
                                <td>
                                    <a class="btn btn-danger" href="<?php echo $this->baseUrl() ?>/user/delete/user_id/<?php echo $this->users[$i]['user_id']; ?>" > Delete </a>
                                </td>
                                </tr
                                <?php
                            }
                            ?>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>
