<html>
    <body>
        <div class="container">
            <div class="col-md-offset-2 col-md-8">       
                <div class="panel panel-info">
                    <div class="panel-heading" > 
                        <h3 class="panel-title">
                            Material 
                        </h3>
                    </div>
                    <div class="panel-body"> 
                        <?php
                        $material_id = $this->material_data[0]['material_id'];
                        $material_name = $this->material_data[0]['material_name'];
                        echo $this->material_data[0]['material_name'];
                        echo '<br>';
                        if ($this->material_data[0]['download_lock'] == 0) { //not locked
                            echo '<a class="btn btn-primary btn-sm" href=' . $this->baseUrl() . '/material/download/material_id/' . $material_id . '>Download</a>';
                            echo '&nbsp';
                            $info = new SplFileInfo("$material_name");
                            $type = $info->getExtension();
                            if ($type == "pptx" || $type == "pdf" || $type = "mp4" || $type == "jpeg" || $type = "jpg") {
                                echo '<a class="btn btn-primary btn-sm" href=' . $this->baseUrl() . '/material/' . $material_name . '>View</a>';
                            }
                        } else {
                            echo '<a class="btn btn-primary btn-sm" href=' . $this->baseUrl() . '/material/' . $material_name . '>View</a>';
                        }
                        echo '<br>';
                        ?>
                    </div>

                </div>  
            </div>
        </div>
    </body>
</html>