<html>
    <body>
        <div class="container">
            <div class="col-md-offset-2 col-md-8">       
                <div class="panel panel-info">
                    <div class="panel-heading" > 
                        <h3 class="panel-title">
                            Material 
                        </h3>
                    </div>
                    <div class="panel-body"> 
                        <?php
                        $authorization = Zend_Auth::getInstance();
                        $user_info = $authorization->getStorage()->read();
                        $material_id = $this->material_data[0]['material_id'];
                        $material_name = $this->material_data[0]['material_name'];
                        echo $this->material_data[0]['material_name'];
                        echo '<br>';
                        if ($this->material_data[0]['download_lock'] == 0) { //not locked
                            if ($authorization->hasIdentity()) {
                                echo '<a class="btn btn-primary btn-sm" href=' . $this->baseUrl() . '/material/download/material_id/' . $material_id . '>Download</a>';
                                echo '&nbsp';
                            }
                            $info = new SplFileInfo("$material_name");
                            $type = $info->getExtension();
                            if ($type == "pptx" || $type == "pdf" || $type = "mp4" || $type == "jpeg" || $type = "jpg") {
                                echo '<a class="btn btn-primary btn-sm" href=' . $this->baseUrl() . '/material/' . $material_name . '>View</a>';
                                echo '&nbsp';
                                echo '<a class="btn btn-primary btn-sm" href=' . $this->baseUrl() . '/user/twitter/materialname/'.$material_name.'>Share Via Twitter</a>';
                            }
                        } else {
                            echo '<a class="btn btn-primary btn-sm" href=' . $this->baseUrl() . '/material/' . $material_name . '>View</a>';
                            echo '&nbsp';
                            echo '<a class="btn btn-primary btn-sm" href=' . $this->baseUrl() . '/user/twitter/materialname/'.$material_name.'>Share Via Twitter</a>';
                        }
                        echo '<br>';
                        ?>
                    </div>
                </div>
                <label>Comments</label>
                <div>
                    <div id='comments'>
                        <?php
                        for ($i = 0; $i < count($this->comments); $i++) {
                            $comment_id = $this->comments[$i]['comment_id'];
                            $comment_text = $this->comments[$i]['comment_text'];
                            $user_name = $this->comments[$i]['user_id'][0];
                            $user_photo = $this->comments[$i]['user_id'][1];
                            $usercomment_id = $this->comments[$i]['user_id'][2];
                            echo '<p id=' . $comment_id . '>';
                            echo "<img src='/zend-project/public/images/users/$user_photo' width='60' height='60'/>";
                            echo '<b style="color:blue">' . $user_name . '</b>';
                            echo '&nbsp';
                            echo $comment_text;
                            if ($authorization->hasIdentity()) {
                                if ($user_info != NULL) {
                                    $user_id = $user_info->user_id;
                                    $admin = $user_info->is_admin;
                                    if ($user_id == $usercomment_id || $admin == 1) {
                                        echo '<button style="float:right;margin-left:3px" class="btn btn-danger btn-sm" onclick="deletecomment(' . $comment_id . ')" >Delete</button>';
                                        echo '<button style="float:right" class="btn btn-primary btn-sm" onclick="editcomment(' . $comment_id . ')" >Edit</button>';
                                    }
                                }
                            }
                            echo '</p>';
                        }
                        ?>
                    </div>
                    <?php
                    if ($authorization->hasIdentity()) {
                        if ($user_info != NULL) {
                            $user_banned = $user_info->is_banned;
                            if ($user_banned == 0) {
                                ?>
                                <input id='comment' class="form-control" type="text" name="comment" placeholder='Enter Your comment ...'>
                                <br>
                                <button class="btn btn-primary btn-sm" onclick="addcomment(<?php echo $material_id ?>)">Add Comment</button>
                                <?php
                            }
                        }
                    }
                    ?>
                </div>
            </div>
        </div>
        <script>
            function addcomment(materialid) {
                var commenttext = document.getElementById('comment').value;
                if (window.XMLHttpRequest) {
                    ajaxRequest = new XMLHttpRequest();
                }
                else {
                    ajaxRequest = new ActiveXObject("Microsoft.XMLHTTP");
                }
                ajaxRequest.open("GET", "/zend-project/public/comment/add?comment_text=" + commenttext + "&materialid=" + materialid, true);
                ajaxRequest.send();
                ajaxRequest.onreadystatechange = function () {
                    if (ajaxRequest.readyState === 4 && ajaxRequest.status === 200) {
                        var comment_id = ajaxRequest.responseText;
                        var commentbody = document.createElement('p'); //parag of comment
                        commentbody.setAttribute('id', comment_id);
                        document.getElementById('comments').appendChild(commentbody);
                        ajaxRequest.open('GET', "/zend-project/public/comment/select?comment_id=" + comment_id, true);
                        ajaxRequest.send();
                        ajaxRequest.onreadystatechange = function () {
                            if (ajaxRequest.readyState === 4 && ajaxRequest.status === 200) {
                                var user_name = JSON.parse(ajaxRequest.responseText)[0];
                                var user_photo = JSON.parse(ajaxRequest.responseText)[1];
                                var img = document.createElement('img');
                                img.setAttribute('src', '/zend-project/public/images/users/' + user_photo);
                                img.setAttribute('height', '60');
                                img.setAttribute('width', '60');
                                commentbody.appendChild(img);
                                var usernamebody = document.createElement('b');
                                usernamebody.setAttribute('style', 'color:blue');
                                usernamebody.innerHTML = user_name;
                                commentbody.appendChild(usernamebody);
                                commentbody.innerHTML += " " + commenttext;
                                document.getElementById('comment').value = "";
                                var delete_button = document.createElement('button');
                                delete_button.setAttribute('style', 'float:right;margin-left:3px');
                                var t = document.createTextNode("Delete");
                                delete_button.appendChild(t);
                                delete_button.setAttribute('class', 'btn btn-danger btn-sm');
                                delete_button.onclick = function () {
                                    deletecomment(comment_id);
                                };
                                commentbody.appendChild(delete_button);
                                var edit_button = document.createElement('button');
                                edit_button.setAttribute('style', 'float:right');
                                var tr = document.createTextNode("Edit");
                                edit_button.appendChild(tr);
                                edit_button.setAttribute('class', 'btn btn-primary btn-sm');
                                edit_button.onclick = function () {
                                    editcomment(comment_id);
                                };
                                commentbody.appendChild(edit_button);

                            }
                        };
                    }
                };
            }

            function deletecomment(comment_id) {
                if (window.XMLHttpRequest) {
                    ajaxRequest = new XMLHttpRequest();
                }
                else {
                    ajaxRequest = new ActiveXObject("Microsoft.XMLHTTP");
                }
                ajaxRequest.open("GET", "/zend-project/public/comment/delete?comment_id=" + comment_id, true);
                ajaxRequest.send();
                ajaxRequest.onreadystatechange = function () {
                    if (ajaxRequest.readyState === 4 && ajaxRequest.status === 200) {
                        var commentbody = document.getElementById(comment_id);
                        commentbody.parentNode.removeChild(commentbody);

                    }
                };
            }

            function editcomment(comment_id) {
                var commentbody = document.getElementById(comment_id);
                var edit_button = commentbody.childNodes[4];
                edit_button.setAttribute('disabled', 'true');
                var last_text = commentbody.childNodes[2].data;
                var comment_edit = document.createElement('input');
                comment_edit.setAttribute('type', 'text');
                comment_edit.setAttribute('value', last_text);
                comment_edit.setAttribute('class', 'form-control');
                var br = document.createElement('br');
                commentbody.appendChild(br);
                commentbody.appendChild(comment_edit);
                comment_edit.onkeydown = function (e) {
                    if (e.keyCode === 13) {
                        var edit_text = commentbody.childNodes[6].value;
                        if (window.XMLHttpRequest) {
                            ajaxRequest = new XMLHttpRequest();
                        }
                        else {
                            ajaxRequest = new ActiveXObject("Microsoft.XMLHTTP");
                        }
                        ajaxRequest.open("GET", "/zend-project/public/comment/edit?comment_id=" + comment_id + "&comment_text=" + edit_text, true);
                        ajaxRequest.send();
                        ajaxRequest.onreadystatechange = function () {
                            if (ajaxRequest.readyState === 4 && ajaxRequest.status === 200) {
                                commentbody.childNodes[2].data = " " + edit_text;
                                comment_edit.parentNode.removeChild(comment_edit);
                                edit_button.removeAttribute('disabled');
                            }
                        };
                    }

                };


            }
        </script>
    </body>
</html>